site_name: mtcli
repo_url: https://github.com/vfranca/mtcli
site_url: https://vfranca.github.io/mtcli
theme:
  name: readthedocs
nav:
  - Início: index.md
  - Instalação: install.md
  - Como Usar: usage.md
  - Subcomandos:
      - Gráficos (bars): bars.md
      - Configurações (conf): conf.md
  - Plugins: plugins.md
  - Contribuindo: contribute.md

