site_name: mtcli
repo_url: https://github.com/vfranca/mtcli
repo_name: vfranca/mtcli

theme:
  name: mkdocs
  locale: pt_BR

nav:
  - Início: index.md
  - Instalação: install.md
  - Como Usar: usage.md
  - Subcomandos:
    - bars (gráficos): bars.md
    - conf (configurações): conf.md
  - Plugins: plugins.md
  - Contribuindo: contribute.md

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - codehilite
  - footnotes
  - def_list
  - pymdownx.extra
  - pymdownx.highlight
  - pymdownx.superfences
